### ISSUE TITLE
Hey admin This code is not working 😔  "pip install pikepdf"  can you fix it fast ?? 

### ISSUE THREAD

**Issue by Fuckup203** [TermuxHackz/pdfbruter#3]
This code "pip install pikepdf"   
![Uploading Screenshot_2022-04-06-22-13-16-16_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Samu23** [comment]
Hi there,  thanks for reaching out to me.. If the below code doesn't work,
try updating your python and then try python2 -m pip install pikepdf or
python3 -m pip install pikepdf and try again.
Thank you.

**Comment by Fuckup203** [comment]
Hey admin still the error !! 😭
Please help me out . See the image below 👇" python3 -m pip install
pikepdf"

**Comment by Samu23** [comment]
Update your terminal, your pip and your python.
And try again
Another way is to visit pypi website search for the module pikepdf.. And
copy the command and install the latest version.

**Comment by Fuckup203** [comment]
Hey Samu23 i All things right but one last thing is remaining after running " pip install pikepdf "
this it is show that image and please reply fast because i was waiting whole to see you reply 🙂
![Uploading Screenshot_2022-04-08-04-05-37-57_84d3000e3f4017145260f7618db1d683.jpg…]()
Please reply me 😞

**Comment by Fuckup203** [comment]
Every time I running " pip install pikepdf "
Its show in image please solve it 🙏🙏🙏
![Uploading Screenshot_2022-04-10-02-01-52-79_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Fuckup203** [comment]
Hey i think this last error after starting " pip install pikepdf" see the
image below Brodie 😅❤️ it showing this
error and note 👇

note: This error originates from a subprocess, and is likely not a problem
with pip.


 ERROR: Failed building wheel for pikepdf.

**Comment by TermuxHackz** [comment]
Hello there, have you been able to rectify the issue?
